name: Lint Code

on:
  push:
    branches: ["main"]
    paths:
      - "./api-**/"

  pull_request:
    branches: ["main"]
    paths:
      - "./api-**/"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api:
          - api-barberos
          - api-citas

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies for ${{ matrix.api }}
        run: |
          pip install --upgrade pip
          pip install -r ./${{ matrix.api }}/requirements.txt

      - name: Lint ${{ matrix.api }} with Ruff
        run: |
          pip install ruff
          ruff check ./${{ matrix.api }}
